#pragma once
#include "stm32_base.h"

// Power Control
#define GPIO_BRICK1_VALID {GPIOB, {GPIO_PIN_5,  GPIO_MODE_INPUT, GPIO_PULLUP, GPIO_SPEED_HIGH, GPIO_AF0_MCO}}
#define GPIO_BRICK2_VALID {GPIOB, {GPIO_PIN_7,  GPIO_MODE_INPUT, GPIO_PULLUP, GPIO_SPEED_HIGH, GPIO_AF0_MCO}}
#define GPIO_USB_VALID    {GPIOC, {GPIO_PIN_0,  GPIO_MODE_INPUT, GPIO_PULLUP, GPIO_SPEED_HIGH, GPIO_AF0_MCO}}
#define GPIO_SENSORS_EN   {GPIOE, {GPIO_PIN_3,  GPIO_MODE_OUTPUT_PP, GPIO_NOPULL, GPIO_SPEED_HIGH, GPIO_AF0_MCO}}
#define GPIO_PERIPH_EN    {GPIOA, {GPIO_PIN_8,  GPIO_MODE_OUTPUT_PP, GPIO_NOPULL, GPIO_SPEED_HIGH, GPIO_AF0_MCO}}
#define GPIO_PERIPH_OC    {GPIOE, {GPIO_PIN_15, GPIO_MODE_INPUT, GPIO_PULLUP, GPIO_SPEED_HIGH, GPIO_AF0_MCO}}
#define GPIO_HIPWR_OC     {GPIOE, {GPIO_PIN_10, GPIO_MODE_INPUT, GPIO_PULLUP, GPIO_SPEED_HIGH, GPIO_AF0_MCO}}

// Debug USART7 bus
#define GPIO_USART7_RX    {GPIOE, {GPIO_PIN_7, GPIO_MODE_AF_PP, GPIO_PULLUP, GPIO_SPEED_FREQ_HIGH, GPIO_AF7_UART7}}
#define GPIO_USART7_TX    {GPIOE, {GPIO_PIN_8, GPIO_MODE_AF_PP, GPIO_PULLUP, GPIO_SPEED_FREQ_HIGH, GPIO_AF7_UART7}}

// ADC channels
#define GPIO_ADC12_INP14  {GPIOA, {GPIO_PIN_2,  GPIO_MODE_ANALOG, GPIO_NOPULL, GPIO_SPEED_FREQ_VERY_HIGH, GPIO_AF0_MCO}}
#define GPIO_ADC12_INP15  {GPIOA, {GPIO_PIN_3,  GPIO_MODE_ANALOG, GPIO_NOPULL, GPIO_SPEED_FREQ_VERY_HIGH, GPIO_AF0_MCO}}
#define GPIO_ADC12_INP18  {GPIOA, {GPIO_PIN_4,  GPIO_MODE_ANALOG, GPIO_NOPULL, GPIO_SPEED_FREQ_VERY_HIGH, GPIO_AF0_MCO}}
#define GPIO_ADC12_INP13  {GPIOC, {GPIO_PIN_3,  GPIO_MODE_ANALOG, GPIO_NOPULL, GPIO_SPEED_FREQ_VERY_HIGH, GPIO_AF0_MCO}}
#define GPIO_ADC12_INP4   {GPIOC, {GPIO_PIN_4,  GPIO_MODE_ANALOG, GPIO_NOPULL, GPIO_SPEED_FREQ_VERY_HIGH, GPIO_AF0_MCO}}
#define GPIO_ADC12_INP8   {GPIOC, {GPIO_PIN_5,  GPIO_MODE_ANALOG, GPIO_NOPULL, GPIO_SPEED_FREQ_VERY_HIGH, GPIO_AF0_MCO}}

// Sensors SPI1 bus
#define GPIO_SPI1_SCK     {GPIOA, {GPIO_PIN_5,  GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_VERY_HIGH, GPIO_AF5_SPI1}}
#define GPIO_SPI1_MISO    {GPIOA, {GPIO_PIN_6,  GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_VERY_HIGH, GPIO_AF5_SPI1}}
#define GPIO_SPI1_MOSI    {GPIOA, {GPIO_PIN_7,  GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_VERY_HIGH, GPIO_AF5_SPI1}}
// ICM20649
#define GPIO_SPI1_CS1     {GPIOC, {GPIO_PIN_2,  GPIO_MODE_OUTPUT_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH, GPIO_AF5_SPI1}}
#define GPIO_SPI1_DRDY1   {GPIOD, {GPIO_PIN_15, GPIO_MODE_IT_RISING, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH, 0}}
#define EXTI_SPI1_DRDY1   {GPIO_SPI1_DRDY1, {EXTI_LINE_15, EXTI_MODE_INTERRUPT, EXTI_TRIGGER_RISING, EXTI_GPIOD}, {EXTI_LINE_15, NULL}, 6, 0}
// MS5611
#define GPIO_SPI1_CS2     {GPIOD, {GPIO_PIN_7,  GPIO_MODE_OUTPUT_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH, GPIO_AF5_SPI1}}

// Flash SPI2 bus
#define GPIO_SPI2_SCK     {GPIOB, {GPIO_PIN_13,  GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_VERY_HIGH, GPIO_AF5_SPI2}}
#define GPIO_SPI2_MISO    {GPIOB, {GPIO_PIN_14,  GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_VERY_HIGH, GPIO_AF5_SPI2}}
#define GPIO_SPI2_MOSI    {GPIOB, {GPIO_PIN_15,  GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_VERY_HIGH, GPIO_AF5_SPI2}}
#define GPIO_SPI2_CS2     {GPIOD, {GPIO_PIN_10,  GPIO_MODE_OUTPUT_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH, GPIO_AF5_SPI2}}

// Sensors SPI4 bus
#define GPIO_SPI4_SCK     {GPIOE, {GPIO_PIN_2,  GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_VERY_HIGH, GPIO_AF5_SPI4}}
#define GPIO_SPI4_MISO    {GPIOE, {GPIO_PIN_5,  GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_VERY_HIGH, GPIO_AF5_SPI4}}
#define GPIO_SPI4_MOSI    {GPIOE, {GPIO_PIN_6,  GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_VERY_HIGH, GPIO_AF5_SPI4}}
// ICM20948
#define GPIO_SPI4_CS1     {GPIOE, {GPIO_PIN_4,  GPIO_MODE_OUTPUT_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH, GPIO_AF5_SPI4}}
// ICM20602
#define GPIO_SPI4_CS2     {GPIOC, {GPIO_PIN_13, GPIO_MODE_OUTPUT_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH, GPIO_AF5_SPI4}}
// MS5611
#define GPIO_SPI4_CS3     {GPIOC, {GPIO_PIN_14, GPIO_MODE_OUTPUT_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH, GPIO_AF5_SPI4}}

// SD card SDMMC1 bus
#define GPIO_SDMMC1_CK    {GPIOC, {GPIO_PIN_12, GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_HIGH, GPIO_AF12_SDMMC1}}
#define GPIO_SDMMC1_CMD   {GPIOD, {GPIO_PIN_2,  GPIO_MODE_AF_PP, GPIO_PULLUP, GPIO_SPEED_HIGH, GPIO_AF12_SDMMC1}}
#define GPIO_SDMMC1_D0    {GPIOC, {GPIO_PIN_8,  GPIO_MODE_AF_PP, GPIO_PULLUP, GPIO_SPEED_HIGH, GPIO_AF12_SDMMC1}}
#define GPIO_SDMMC1_D1    {GPIOC, {GPIO_PIN_9,  GPIO_MODE_AF_PP, GPIO_PULLUP, GPIO_SPEED_HIGH, GPIO_AF12_SDMMC1}}
#define GPIO_SDMMC1_D2    {GPIOC, {GPIO_PIN_10, GPIO_MODE_AF_PP, GPIO_PULLUP, GPIO_SPEED_HIGH, GPIO_AF12_SDMMC1}}
#define GPIO_SDMMC1_D3    {GPIOC, {GPIO_PIN_11, GPIO_MODE_AF_PP, GPIO_PULLUP, GPIO_SPEED_HIGH, GPIO_AF12_SDMMC1}}
#define GPIO_SDMMC1_CD    {GPIOG, {GPIO_PIN_0,  GPIO_MODE_INPUT, GPIO_NOPULL, GPIO_SPEED_HIGH, GPIO_AF0_MCO}}

// PX4IO USART6 bus
#define GPIO_USART6_RX    {GPIOC, {GPIO_PIN_7, GPIO_MODE_AF_PP, GPIO_PULLUP, GPIO_SPEED_FREQ_HIGH, GPIO_AF8_USART6}}
#define GPIO_USART6_TX    {GPIOC, {GPIO_PIN_6, GPIO_MODE_AF_PP, GPIO_PULLUP, GPIO_SPEED_FREQ_HIGH, GPIO_AF8_USART6}}

// USB bus
#define GPIO_OTG_FS_VBUS  {GPIOA, {GPIO_PIN_9, GPIO_MODE_INPUT, GPIO_PULLDOWN, GPIO_SPEED_FREQ_VERY_HIGH, 0}}
#define GPIO_OTG_FS_DM    {GPIOA, {GPIO_PIN_11, GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_VERY_HIGH, GPIO_AF10_OTG_FS}}
#define GPIO_OTG_FS_DP    {GPIOA, {GPIO_PIN_12, GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_VERY_HIGH, GPIO_AF10_OTG_FS}}
