#include "stm32_base.h"

// Serial console
#define GPIO_USART7_RX    {GPIOF, {GPIO_PIN_6, GPIO_MODE_INPUT, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH, GPIO_AF8_UART7}}
#define GPIO_USART7_TX    {GPIOE, {GPIO_PIN_8, GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH, GPIO_AF8_UART7}}

// Sensors
#define GPIO_SPI1_MISO    {GPIOA, {GPIO_PIN_6,  GPIO_MODE_AF_, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH, GPIO_AF5_SPI1}}
#define GPIO_SPI1_MOSI    {GPIOD, {GPIO_PIN_7,  GPIO_MODE_INPUT, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH, GPIO_AF5_SPI1}}
#define GPIO_SPI1_SCK     {GPIOG, {GPIO_PIN_11, GPIO_MODE_INPUT, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH, GPIO_AF5_SPI1}}
