#include "stm32_base.h"

// Serial console
#define GPIO_USART7_RX    {GPIOF, {GPIO_PIN_6, GPIO_MODE_INPUT, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH, GPIO_AF8_UART7}}
#define GPIO_USART7_TX    {GPIOE, {GPIO_PIN_8, GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH, GPIO_AF8_UART7}}

// Sensors SPI bus
#define GPIO_SPI1_MISO    {GPIOA, {GPIO_PIN_6,  GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_VERY_HIGH, GPIO_AF5_SPI1}}
#define GPIO_SPI1_MOSI    {GPIOD, {GPIO_PIN_7,  GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_VERY_HIGH, GPIO_AF5_SPI1}}
#define GPIO_SPI1_SCK     {GPIOG, {GPIO_PIN_11, GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_VERY_HIGH, GPIO_AF5_SPI1}}
// ICM20689
#define GPIO_SPI1_CS1     {GPIOF, {GPIO_PIN_2,  GPIO_MODE_OUTPUT_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH, GPIO_AF5_SPI1}}
#define GPIO_SPI1_DRDY1   {GPIOB, {GPIO_PIN_4,  GPIO_MODE_IT_RISING, GPIO_PULLUP, GPIO_SPEED_FREQ_HIGH, GPIO_AF5_SPI1}}
// ICM20602  
#define GPIO_SPI1_CS2     {GPIOF, {GPIO_PIN_3,  GPIO_MODE_OUTPUT_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH, GPIO_AF5_SPI1}}
#define GPIO_SPI1_DRDY2   {GPIOC, {GPIO_PIN_5,  GPIO_MODE_IT_RISING, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH, GPIO_AF5_SPI1}}
// BMI055_GYR
#define GPIO_SPI1_CS3     {GPIOF, {GPIO_PIN_4,  GPIO_MODE_OUTPUT_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH, GPIO_AF5_SPI1}}
#define GPIO_SPI1_DRDY3   {GPIOB, {GPIO_PIN_14, GPIO_MODE_IT_RISING, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH, GPIO_AF5_SPI1}}
// BMI055_ACC
#define GPIO_SPI1_CS4     {GPIOG, {GPIO_PIN_10, GPIO_MODE_OUTPUT_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH, GPIO_AF5_SPI1}}
#define GPIO_SPI1_DRDY4   {GPIOB, {GPIO_PIN_15, GPIO_MODE_IT_RISING, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH, GPIO_AF5_SPI1}}
