#include "core.h"
#include "hal.h"
#include "board.h"

// PWR
gpio_t gpio_brick1_valid = {GPIOB, {GPIO_PIN_5,  GPIO_MODE_INPUT, GPIO_PULLUP, GPIO_SPEED_HIGH, GPIO_AF0_MCO}};
gpio_t gpio_brick2_valid = {GPIOB, {GPIO_PIN_7,  GPIO_MODE_INPUT, GPIO_PULLUP, GPIO_SPEED_HIGH, GPIO_AF0_MCO}};
gpio_t gpio_usb_valid    = {GPIOC, {GPIO_PIN_0,  GPIO_MODE_INPUT, GPIO_PULLUP, GPIO_SPEED_HIGH, GPIO_AF0_MCO}};
gpio_t gpio_sensors_en   = {GPIOE, {GPIO_PIN_3,  GPIO_MODE_OUTPUT_PP, GPIO_NOPULL, GPIO_SPEED_HIGH, GPIO_AF0_MCO}};
gpio_t gpio_periph_en    = {GPIOA, {GPIO_PIN_8,  GPIO_MODE_OUTPUT_PP, GPIO_NOPULL, GPIO_SPEED_HIGH, GPIO_AF0_MCO}};
gpio_t gpio_periph_oc    = {GPIOE, {GPIO_PIN_15, GPIO_MODE_INPUT, GPIO_PULLUP, GPIO_SPEED_HIGH, GPIO_AF0_MCO}};
gpio_t gpio_hipwr_oc     = {GPIOE, {GPIO_PIN_10, GPIO_MODE_INPUT, GPIO_PULLUP, GPIO_SPEED_HIGH, GPIO_AF0_MCO}};

// ADC
gpio_t gpio_adc_inp14 = {GPIOA, {GPIO_PIN_2,  GPIO_MODE_ANALOG, GPIO_NOPULL, GPIO_SPEED_FREQ_VERY_HIGH, GPIO_AF0_MCO}};
gpio_t gpio_adc_inp15 = {GPIOA, {GPIO_PIN_3,  GPIO_MODE_ANALOG, GPIO_NOPULL, GPIO_SPEED_FREQ_VERY_HIGH, GPIO_AF0_MCO}};
gpio_t gpio_adc_inp18 = {GPIOA, {GPIO_PIN_4,  GPIO_MODE_ANALOG, GPIO_NOPULL, GPIO_SPEED_FREQ_VERY_HIGH, GPIO_AF0_MCO}};
gpio_t gpio_adc_inp13 = {GPIOC, {GPIO_PIN_3,  GPIO_MODE_ANALOG, GPIO_NOPULL, GPIO_SPEED_FREQ_VERY_HIGH, GPIO_AF0_MCO}};
gpio_t gpio_adc_inp4  = {GPIOC, {GPIO_PIN_4,  GPIO_MODE_ANALOG, GPIO_NOPULL, GPIO_SPEED_FREQ_VERY_HIGH, GPIO_AF0_MCO}};
gpio_t gpio_adc_inp8  = {GPIOC, {GPIO_PIN_5,  GPIO_MODE_ANALOG, GPIO_NOPULL, GPIO_SPEED_FREQ_VERY_HIGH, GPIO_AF0_MCO}};

// Sensors SPI1 bus
gpio_t gpio_spi1_sck  = {GPIOA, {GPIO_PIN_5,  GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_VERY_HIGH, GPIO_AF5_SPI1}};
gpio_t gpio_spi1_miso = {GPIOA, {GPIO_PIN_6,  GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_VERY_HIGH, GPIO_AF5_SPI1}};
gpio_t gpio_spi1_mosi = {GPIOA, {GPIO_PIN_7,  GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_VERY_HIGH, GPIO_AF5_SPI1}};
// ICM20649
gpio_t gpio_spi1_cs1   = {GPIOC, {GPIO_PIN_2,  GPIO_MODE_OUTPUT_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH, GPIO_AF0_MCO}};
// MS5611
gpio_t gpio_spi1_cs2 = {GPIOD, {GPIO_PIN_7,  GPIO_MODE_OUTPUT_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH, GPIO_AF0_MCO}};

// Flash SPI2 bus
gpio_t gpio_spi2_sck  = {GPIOB, {GPIO_PIN_13,  GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_VERY_HIGH, GPIO_AF5_SPI2}};
gpio_t gpio_spi2_miso = {GPIOB, {GPIO_PIN_14,  GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_VERY_HIGH, GPIO_AF5_SPI2}};
gpio_t gpio_spi2_mosi = {GPIOB, {GPIO_PIN_15,  GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_VERY_HIGH, GPIO_AF5_SPI2}};
gpio_t gpio_spi2_cs1  = {GPIOD, {GPIO_PIN_10,  GPIO_MODE_OUTPUT_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH, GPIO_AF0_MCO}};

// Sensors SPI4 bus
gpio_t gpio_spi4_sck  = {GPIOE, {GPIO_PIN_2,  GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_VERY_HIGH, GPIO_AF5_SPI4}};
gpio_t gpio_spi4_miso = {GPIOE, {GPIO_PIN_5,  GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_VERY_HIGH, GPIO_AF5_SPI4}};
gpio_t gpio_spi4_mosi = {GPIOE, {GPIO_PIN_6,  GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_VERY_HIGH, GPIO_AF5_SPI4}};
// ICM20948
gpio_t gpio_spi4_cs1 = {GPIOE, {GPIO_PIN_4,  GPIO_MODE_OUTPUT_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH, GPIO_AF0_MCO}};
// ICM20602
gpio_t gpio_spi4_cs2 = {GPIOC, {GPIO_PIN_13, GPIO_MODE_OUTPUT_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH, GPIO_AF0_MCO}};
// MS5611
gpio_t gpio_spi4_cs3 = {GPIOC, {GPIO_PIN_14, GPIO_MODE_OUTPUT_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH, GPIO_AF0_MCO}};
// ACCEL MAG
gpio_t gpio_spi4_cs4 = {GPIOC, {GPIO_PIN_15, GPIO_MODE_OUTPUT_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH, GPIO_AF0_MCO}};

// SD card SDMMC1 bus
gpio_t gpio_sdmmc1_ck  = {GPIOC, {GPIO_PIN_12, GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_HIGH, GPIO_AF12_SDMMC1}};
gpio_t gpio_sdmmc1_cmd = {GPIOD, {GPIO_PIN_2,  GPIO_MODE_AF_PP, GPIO_PULLUP, GPIO_SPEED_HIGH, GPIO_AF12_SDMMC1}};
gpio_t gpio_sdmmc1_d0  = {GPIOC, {GPIO_PIN_8,  GPIO_MODE_AF_PP, GPIO_PULLUP, GPIO_SPEED_HIGH, GPIO_AF12_SDMMC1}};
gpio_t gpio_sdmmc1_d1  = {GPIOC, {GPIO_PIN_9,  GPIO_MODE_AF_PP, GPIO_PULLUP, GPIO_SPEED_HIGH, GPIO_AF12_SDMMC1}};
gpio_t gpio_sdmmc1_d2  = {GPIOC, {GPIO_PIN_10, GPIO_MODE_AF_PP, GPIO_PULLUP, GPIO_SPEED_HIGH, GPIO_AF12_SDMMC1}};
gpio_t gpio_sdmmc1_d3  = {GPIOC, {GPIO_PIN_11, GPIO_MODE_AF_PP, GPIO_PULLUP, GPIO_SPEED_HIGH, GPIO_AF12_SDMMC1}};
gpio_t gpio_sdmmc1_cd  = {GPIOG, {GPIO_PIN_0,  GPIO_MODE_INPUT, GPIO_NOPULL, GPIO_SPEED_HIGH, GPIO_AF0_MCO}};

// TELEM1 USART2 bus
gpio_t gpio_usart2_tx = {GPIOD, {GPIO_PIN_5, GPIO_MODE_AF_PP, GPIO_PULLUP, GPIO_SPEED_FREQ_HIGH, GPIO_AF7_USART2}};
gpio_t gpio_usart2_rx = {GPIOD, {GPIO_PIN_6, GPIO_MODE_AF_PP, GPIO_PULLUP, GPIO_SPEED_FREQ_HIGH, GPIO_AF7_USART2}};

// TELEM2 USART3 bus
gpio_t gpio_usart3_tx = {GPIOD, {GPIO_PIN_8, GPIO_MODE_AF_PP, GPIO_PULLUP, GPIO_SPEED_FREQ_HIGH, GPIO_AF7_USART3}};
gpio_t gpio_usart3_rx = {GPIOD, {GPIO_PIN_9, GPIO_MODE_AF_PP, GPIO_PULLUP, GPIO_SPEED_FREQ_HIGH, GPIO_AF7_USART3}};

// GPS1 USART4 bus
gpio_t gpio_usart4_tx = {GPIOA, {GPIO_PIN_0, GPIO_MODE_AF_PP, GPIO_PULLUP, GPIO_SPEED_FREQ_HIGH, GPIO_AF8_UART4}};
gpio_t gpio_usart4_rx = {GPIOA, {GPIO_PIN_1, GPIO_MODE_AF_PP, GPIO_PULLUP, GPIO_SPEED_FREQ_HIGH, GPIO_AF8_UART4}};

// GPS2 I2C1 bus
gpio_t gpio_i2c1_scl  = {GPIOB, {GPIO_PIN_8, GPIO_MODE_AF_OD, GPIO_NOPULL, GPIO_SPEED_FREQ_VERY_HIGH, GPIO_AF4_I2C1}};
gpio_t gpio_i2c1_sda  = {GPIOB, {GPIO_PIN_9, GPIO_MODE_AF_OD, GPIO_NOPULL, GPIO_SPEED_FREQ_VERY_HIGH, GPIO_AF4_I2C1}};

// IO USART6 bus
gpio_t gpio_usart6_tx = {GPIOC, {GPIO_PIN_6, GPIO_MODE_AF_PP, GPIO_PULLUP, GPIO_SPEED_FREQ_HIGH, GPIO_AF7_USART6}};
gpio_t gpio_usart6_rx = {GPIOC, {GPIO_PIN_7, GPIO_MODE_AF_PP, GPIO_PULLUP, GPIO_SPEED_FREQ_HIGH, GPIO_AF7_USART6}};

// DEBUG USART7 bus
gpio_t gpio_usart7_tx = {GPIOE, {GPIO_PIN_8, GPIO_MODE_AF_PP, GPIO_PULLUP, GPIO_SPEED_FREQ_HIGH, GPIO_AF7_UART7}};
gpio_t gpio_usart7_rx = {GPIOE, {GPIO_PIN_7, GPIO_MODE_AF_PP, GPIO_PULLUP, GPIO_SPEED_FREQ_HIGH, GPIO_AF7_UART7}};

// GPS2 USART8 bus
gpio_t gpio_usart8_tx = {GPIOE, {GPIO_PIN_1, GPIO_MODE_AF_PP, GPIO_PULLUP, GPIO_SPEED_FREQ_HIGH, GPIO_AF8_UART8}};
gpio_t gpio_usart8_rx = {GPIOE, {GPIO_PIN_0, GPIO_MODE_AF_PP, GPIO_PULLUP, GPIO_SPEED_FREQ_HIGH, GPIO_AF8_UART8}};

// GPS2 I2C2 bus
gpio_t gpio_i2c2_scl  = {GPIOB, {GPIO_PIN_10, GPIO_MODE_AF_OD, GPIO_NOPULL, GPIO_SPEED_FREQ_VERY_HIGH, GPIO_AF4_I2C2}};
gpio_t gpio_i2c2_sda  = {GPIOB, {GPIO_PIN_11, GPIO_MODE_AF_OD, GPIO_NOPULL, GPIO_SPEED_FREQ_VERY_HIGH, GPIO_AF4_I2C2}};

// FMU PWM
gpio_t gpio_fmu_pwm[6] = {
    {GPIOE, {GPIO_PIN_14,  GPIO_MODE_OUTPUT_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_VERY_HIGH, GPIO_AF0_MCO}},
    {GPIOE, {GPIO_PIN_13,  GPIO_MODE_OUTPUT_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_VERY_HIGH, GPIO_AF0_MCO}},
    {GPIOE, {GPIO_PIN_11,  GPIO_MODE_OUTPUT_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_VERY_HIGH, GPIO_AF0_MCO}},
    {GPIOE, {GPIO_PIN_9,   GPIO_MODE_OUTPUT_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_VERY_HIGH, GPIO_AF0_MCO}},
    {GPIOD, {GPIO_PIN_13,  GPIO_MODE_OUTPUT_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_VERY_HIGH, GPIO_AF0_MCO}},
    {GPIOD, {GPIO_PIN_14,  GPIO_MODE_OUTPUT_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_VERY_HIGH, GPIO_AF0_MCO}},
};

// CAN1 bus
gpio_t gpio_can1_rx  = {GPIOD, {GPIO_PIN_0,  GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_VERY_HIGH, GPIO_AF9_FDCAN1}};
gpio_t gpio_can1_tx  = {GPIOD, {GPIO_PIN_1, GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_VERY_HIGH, GPIO_AF9_FDCAN1}};

// CAN2 bus
gpio_t gpio_can2_rx  = {GPIOB, {GPIO_PIN_12, GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_VERY_HIGH, GPIO_AF9_FDCAN2}};
gpio_t gpio_can2_tx  = {GPIOB, {GPIO_PIN_6, GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_VERY_HIGH, GPIO_AF9_FDCAN2}};

// OTG_FS bus
gpio_t gpio_otg_fs_dp  = {GPIOA, {GPIO_PIN_12, GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_VERY_HIGH, GPIO_AF12_OTG1_FS}};
gpio_t gpio_otg_fs_dm  = {GPIOA, {GPIO_PIN_11, GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_VERY_HIGH, GPIO_AF12_OTG1_FS}};
